version: "3.2"
services:
  webserver:
    image: spring-mybatis-example:tomcat
    container_name: spring-mybatis-tomcat
    tty: true
    restart: always
    ports:
      - 5010:8080
    networks:
      - spring-mybatis-webnet
  database:
    image: mysql:8.0-debian
    container_name: spring-mybatis-mysql
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hWN78krBId
      MYSQL_DATABASE: kGLMBWqXmZ
      MYSQL_USER: kGLMBWqXmZ
      MYSQL_PASSWORD: hWN78krBId
    volumes:
      - /var/mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 5020:3306
    networks:
      - spring-mybatis-webnet
  adminer:
    image: adminer
    container_name: spring-mybatis-adminer
    restart: always
    ports:
      - 5030:8080
    networks:
      - spring-mybatis-webnet
networks:
  spring-mybatis-webnet:
    ipam:
      config:
        - subnet: 192.168.1.0/24
